require('settings')
require('mappings')
require('nvim-tree-config')
require('telescope-config')
require('treesitter-config')
require('toggleterm-config')
require('lsp-config')
require('lsp_lines-config')
require('sort')
require('blame')
require('trouble-config')
-- require('airline-config')
-- require('tabby-config')
-- require('scope-config')
require('cinnamon-config')
require('barbar-config')
require('noice-config')
require('twilight-config')
require('venv-selector-config')
require('yazi-config')
